### ISSUE TITLE
Issue with redirect 

### ISSUE THREAD

**Issue by emillod** [dubas-pro/ext-short-url#2]
Hello,
until recently the extension worked. But since one of the last updates I only get a page with the word "true".
No redirect anymore....
Everything is still correct in the .htaccess.​

https://forum.espocrm.com/forum/extensions/73752-short-url-extension-for-espocrm-free-extension?p=94481#post94481

**Comment by ChrisSka** [comment]
Hello,
I do not know what was running differently now, but the error has somehow disappeared.
I just moved the Espo instance to another subdomain yesterday, but the same server. Now I happened to test again and it works without problems.
Ok, I just tested a new feature at Plesk, called Performance Boost, there you can optimize the webserver and PHP settings, maybe it was because of that. And only tested afterwards.
So from my side, this can also be closed again.

**Comment by emillod** [comment]
Fixed in the newest version. 
https://github.com/dubas-pro/ext-short-url/releases/tag/1.0.0
